CREATE TABLE Parts (
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NOT NULL,
	Number NVARCHAR(50) NOT NULL,
	Cost DECIMAL(18,2) NOT NULL DEFAULT 0,
	SellingPrice DECIMAL(18,2) NOT NULL DEFAULT 0,
	VendorId INT NOT NULL,
	CreatedAt DATETIME2 DEFAULT GETDATE(),
	CONSTRAINT FK_Vendors_Parts FOREIGN KEY (VendorId) REFERENCES Vendors(Id)
)