CREATE TABLE Records (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Number NVARCHAR(50) NOT NULL,
	TrxId INT NOT NULL,
	TrxType INT NOT NULL,
	PartId INT NOT NULL,
	Quantity INT NOT NULL,
	Pirce DECIMAL(18,2) NOT NULL DEFAULT 0,
	Total DECIMAL(18,2) NOT NULL DEFAULT 0,
	TrxDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	CreatedAt DATETIME2 DEFAULT GETDATE(),
	CONSTRAINT FK_Parts_Records FOREIGN KEY (PartId) REFERENCES Parts(Id)
)