CREATE TABLE Vendors (
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NOT NULL,
	Number NVARCHAR(50) NULL,
	Email NVARCHAR(50) NULL,
	[Address] NVARCHAR(100) NULL,
	CreatedAt DATETIME2 DEFAULT GETDATE()
)